### ISSUE TITLE
http请求非200情况，异常日志打印错误。

### ISSUE THREAD

**Issue by goolulu** [jpush/jiguang-sdk-java#5]
异常日志
`cn.jiguang.sdk.exception.ApiErrorException: null
	at cn.jiguang.sdk.codec.ApiErrorDecoder.decode(ApiErrorDecoder.java:20)
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy307.send(Unknown Source)
	at cn.jiguang.sdk.api.PushApi.send(PushApi.java:36)
`
需要在第二张图那里调用 super(apiError.getError().getMessage())
![image](https://github.com/user-attachments/assets/69d21735-5aa7-4605-b20d-422c11aa306c)
![image](https://github.com/user-attachments/assets/e33b87b8-1e52-4927-ae5c-16b5fdcba04a)

**Comment by wicked-tc130** [comment]
感谢，已修改。
